# Generated by Django 5.2.4 on 2025-08-07 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecomapp", "0002_remove_cart_total_amount_remove_cartitem_subtotal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ecomapp.products",
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="cart",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ecomapp.user",
            ),
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
    ]
